<span style = "font-size:20px"> **(1) Create a one dimensinoal array that contains numbers from 1 to 10.**</span><br>
    **Use `np.array()`**

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


<span style = "font-size:20px"> **(2) Create the following arrays** </span><br>
[[15, 12, 9, 22],<br>
 [21, 7, 10, 14],<br>
 [31, 10, 33, 8]]<br>
 **Use `np.array()`**

In [2]:
arr = np.array([
    [15, 12,  9, 22],
    [21,  7, 10, 14],
    [31, 10, 33,  8]
])
print(arr)

[[15 12  9 22]
 [21  7 10 14]
 [31 10 33  8]]


<span style = "font-size:20px"> **(3) Create an array full of zeros and of shape (2,3).**</span><br>
    **Use `np.zeros()`**

In [3]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


<span style = "font-size:20px"> **(4) Create an array that contains odd numbers from 1 to 1000.**</span><br>
**Use: `np.arange()`**

In [4]:
arr = np.arange(1, 1001, 2)  
print("Count:", arr.shape[0])

Count: 500


<span style = "font-size:20px"> **(6) Show what `ndim` do.**</span><br>

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2],[3,4]]])

print(a.ndim)  
print(b.ndim)  
print(c.ndim)  

1
2
3


<span style = "font-size:20px"> **(7) What is the difference between `shape` and `size`?**</span><br>
**Explain with words and with `code`.**

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)  
print(arr.size)  

(2, 3)
6


<span style = "font-size:20px"> **(8) Flat the following array.**</span><br>

In [7]:
arr = np.array([[i, 2*i, 3*i] for i in range(3, 300)])
flat = arr.flatten()   # or arr.ravel()

print("Before shape:", arr.shape)
print("After shape: ", flat.shape)
print(flat[:9])

Before shape: (297, 3)
After shape:  (891,)
[ 3  6  9  4  8 12  5 10 15]


<span style = "font-size:20px"> **(9) Transpose the following array.**</span><br>

In [8]:
arr = np.array([[[[j, j+1] for j in range(5)]] for i in range(3)])
t = arr.T

print("Before shape:", arr.shape)  
print("After shape: ", t.shape)    

Before shape: (3, 1, 5, 2)
After shape:  (2, 5, 1, 3)


<span style = "font-size:20px"> **(10) How many unique values are in the following array and print them.**</span><br>

In [9]:
countries = np.array(['canada','spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan','egypt','india','japan'
                     ,'china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                    ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                    'china','canada','china''canada','germany','russia','japan','india','russia','egypt', 'canada',
                    'spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan',
                    'egypt','india','japan','china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                      ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                      'china','canada','china''canada','germany','russia','japan','india','russia','egypt'])
unique_vals = np.unique(countries)

print("Number of unique countries:", len(unique_vals))
print("Unique countries:", unique_vals)

Number of unique countries: 14
Unique countries: ['canada' 'canadaegypt' 'china' 'chinacanada' 'egypt' 'england' 'germany'
 'india' 'japan' 'russia' 'russiagermanychina' 'spain' 'spainspain' 'usa']


(11) Given the following arrays:

```python
import numpy as np

A = np.arange(1, 13).reshape(3, 4)
B = np.array([10, 20, 30])

### 1. Shapes
What is the shape of:
- `A[1]`  
- `B`

---

### 2. Broadcasting Issue
Why does the following operation fail?

```python
result = A[1] * B



### Question : The Embedding Challenge
You are given two arrays:
1. `array_a`: A 5x5 grid filled with the number `9`.
2. `array_b`: A 3x3 grid filled with the number `1`.

**Task:** Use slicing to "embed" `array_b` into the center of `array_a`. Do **not** use loops.

**Expected Result:**
```python
[[9, 9, 9, 9, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 9, 9, 9, 9]]

In [10]:
array_a = np.full((5, 5), 9)
array_b = np.ones((3, 3))

A = np.arange(1, 13).reshape(3, 4)
B = np.array([10, 20, 30])

print(A[1].shape)  
print(B.shape)     

### Embedding challenge
array_a = np.full((5, 5), 9)
array_b = np.ones((3, 3))

array_a[1:4, 1:4] = array_b

print(array_a)

(4,)
(3,)
[[9 9 9 9 9]
 [9 1 1 1 9]
 [9 1 1 1 9]
 [9 1 1 1 9]
 [9 9 9 9 9]]


##  NumPy Dimensions – Questions

1. What is the shape of `a` and `b`?  

2. What does `(3,)` mean in NumPy? Why is there a comma?  

3. How many dimensions does each array have?  

4. What does each dimension (axis) represent in `b`?  

5. Is `(3,)` the same as `(3, 1)`? Explain the difference.  

In [11]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([[1,2],[3,4],[5,6]])

print("a.shape:", a.shape)    # (3,)
print("b.shape:", b.shape)    # (3, 2)
print("a.ndim: ", a.ndim)     # 1
print("b.ndim: ", b.ndim)     # 2

c = np.array([[10],[20],[30]])  
print("c.shape:", c.shape)

a.shape: (3,)
b.shape: (3, 2)
a.ndim:  1
b.ndim:  2
c.shape: (3, 1)
